#!/bin/bash
# Shortcuts for SSH for NIO assets 
alias mgmt='echo "Touch your YubiKey" ; \
ssh -i ~/.ssh/id_ed25519_sk mchalles@mgmt'
alias cordwain='echo "Touch your YubiKey" ; \
ssh -i ~/.ssh/id_ed25519_sk mchalles@cordwain'
alias vyos1='echo "Touch your YubiKey" ; \
ssh -i ~/.ssh/id_ed25519_sk vyos@172.31.0.1'
alias vyos2='echo "Touch your YubiKey" ; \
ssh -i ~/.ssh/id_ed25519_sk vyos@172.31.0.64'
alias warlock='echo "Touch your YubiKey" ; \
ssh -i ~/.ssh/id_ed25519_sk mchalles@warlock-mchalles'

