#!/bin/bash
# Useful replacements for normal commands
alias ls='ls -F --color=auto'
alias ll='ls -alhF --color=auto'
alias lt='ls --human-readable --size -1 -S'
alias mnt="mount | awk -F' ' '{ printf \"%s\t%s\n\",\$1,\$3; }' | column -t | egrep ^/dev/ | sort"
alias gh='history|grep'
alias rm='rm -I --preserve-root'
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias neovim='nvim'
